
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-10am-2
owner: ucsb-cs156-m23
repo_name: team03-m23-10am-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"Kirill-RecommendationRequest","number":78,"title":"ka - sets up the Index page for the RecommendationRequest (and tests)","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/78"},{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"Kirill-RecReqEdit","number":77,"title":"ka - sets up the Edit page and tests for RecommendationRequest","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/77"},{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-OrgTable-Pages","number":76,"title":"JZ - UCSBOrg Create/Edit/Index + fixed tests issues + app.js + navbar","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/76"},{"author":{"id":"MDQ6VXNlcjc3NzEwNjU5","is_bot":false,"login":"cyrus895","name":""},"headRefName":"CC-MenuItemReviewIndexCreateEdit","number":74,"title":"CC - MenuItemReview Index/Create/Edit w tests","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/74"},{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-DiningCommonsMenu-Debug","number":69,"title":"RG - MenuItem Create/Index/Edit Page + changed Endpoints to lowercase","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/69"}]
