
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-10am-2
owner: ucsb-cs156-m23
repo_name: team03-m23-10am-2
pull_requests: [{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-OrgTable-Table","number":70,"title":"Josh org table + utils + tests","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/70"},{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-DiningCommonsMenu-Debug","number":69,"title":"RG - MenuItem Create/Index/Edit Page + changed Endpoints to lowercase","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/69"},{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-DiningCommonsMenu-Placeholders","number":68,"title":"RG - added placeholder for DiningCommonsMenItem, full coverage tests, and edited two App.js files","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/68"},{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-DiningCommonsMenu-TableComp","number":67,"title":"RG - UCSBDiningCommonsMenuItem Table Component (Table.js, Table.test.js, Table.stories plus full tests)","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/67"},{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"Kirill-RecommendationRequest","number":66,"title":"ka - set up front end Form (with tests and storybook) for RecommendationRequest","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/66"},{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-OrgTable-Component","number":65,"title":"component ucsborg + tests modified boolean select option all tests passed","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/65"},{"author":{"id":"MDQ6VXNlcjc3NzEwNjU5","is_bot":false,"login":"cyrus895","name":""},"headRefName":"CC-ComponentMenuItemReview","number":64,"title":"Cc form component menu item review +  placeholderpages","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/64"},{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-DiningCommonsMenu-FormComp","number":63,"title":"RG - Form Component for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-2/pull/63"}]
